Unleash/unleash-react-sdk

README.md, package.json, src/FlagProvider.test.tsx, src/FlagProvider.tsx, yarn.lock
Problem:
Currently there is no way to wait on the resolution of the new flags for when the unleash context was updated.
Usually there is no problem as you fire updateContext and forget, but you can observe it as a problem when you have a side effect ( like redirecting the page ) and you need the new unleash variants / values before executing the side-effect. (  As an example usually you want to store user variants in analytics for A/B testing ) 
Currently there is no way to wait on the resolution of the flags after the context was updated. This PR addresses this, it has been tested manually and all tests are passing.
This is backwards compatible as consumers can still fire and forget like before, but now can also wait for the updateContext to finish.
Updated to latest …
=> feat: async capabilites for updating context

src/FlagProvider.test.tsx, src/FlagProvider.tsx
Memoize the context provided value, so in a eventual rerender of the Provider, it does not force a rerender of a memoized consumer.
We should never pass a new object to the provider, otherwise it forces the rerender of every consumer. See: https://reactjs.org/docs/context.html#caveats
=> fix: memoize context provider value

src/FlagProvider.test.tsx, src/FlagProvider.tsx
fixes https://github.com/Unleash/proxy-client-react/issues/45
Adds `startClient` option that is used to optionally disable starting the client on `FlagProvider` mount so that the creator can handle responsibility of starting and stopping the client.
Also adds a test to ensure that the client is not started when a client is passed in props and the `startClient` prop is false. This may not be necessary. Please let me know any feedback :)
=> Make starting client on FlagProvider mount optional

README.md
Documents the newly added startClient option. Merge when released.
=> docs: add docs for startClient option

src/FlagProvider.tsx
React 18 will no longer allow "implicit children", so this commit adds
this type to the `IFlagProvider` interface.
=> Add explicit children to `IFlagProvider`

README.md
Updated the README to specify using the named `FlagProvider` export instead of the default export, which was causing issues with Vite prod builds. See linked issue for more information. 
Closes #57.
- `README.md`
We might want to remove the default export at a later major version and only use named exports.
=> docs: update README to use named export instead of default

.github/workflows/release_changelog.yml
Github doesn't allow you to set secrets that starts with GITHUB_ anymore. Had to change the token secret in the workflow to accommodate.
=> fix: token name

src/FlagProvider.test.tsx, src/FlagProvider.tsx
Fix #80: Stop client on unmount
- Handles defensively stopping the client first in case someone passed in a started client for some reason
- On Unmount will stop the client and null out the ref
=> Fix #80: Stop client on unmount

package.json, src/FlagProvider.tsx
I don't think we should set the ref as undefined like in https://github.com/Unleash/proxy-client-react/pull/81, otherwise this breaks in `development`.
Relevant: https://beta.reactjs.org/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development
=> 3.3.1-beta.2

src/FlagProvider.tsx, src/index.ts, src/useFlag.ts, src/useVariant.ts
This PR extracts handlers into their own functions and adds a returning function in the useEffect that cleans up the event listeners on unmount.
Closes #90 
Closes #91
=> fix: extract handlers and add cleanup function

README.md, package.json, src/FlagProvider.test.tsx, src/FlagProvider.tsx, src/integration.test.tsx, src/useVariant.ts, tsconfig.json, yarn.lock
Closes [#98 `useFlagsStatus` always returns `false` for `flagsReady`](https://github.com/Unleash/proxy-client-react/issues/98)
Makes #100 obsolete.
`FlagProvider.tsx`
=> Fix: useFlagsStatus initialization nextjs dev

src/FlagProvider.tsx, src/integration.test.tsx
https://unleash-community.slack.com/archives/C03GWTN7XMG/p1675847730447999
> I can not figure out why useFlag is being updated not at same rate as flagsReadyStatus?
> I mean, my feature flag is on, but when flagsReady is true, it appears to be false, but after a while true
> How can I fix this issue?
=> fix: make sure flagsReady doesn't go before isEnabled

src/useFlag.test.tsx, src/useFlag.ts, src/useVariant.test.tsx, src/useVariant.ts
I discovered that the event listeners are not removed properly in useFlag and useVariant. The original author's intention was correct but a return statement were missing by a mistake. It can cause "Can't perform a React state update on an unmounted component." error and unallocated resources.
Closes #90
I wrote tests first to prove the error so you should start the review with the new tests. The fix is simple, I've just added the missing returns in the implementation.
In the test suites I moved the mockClear calls inside the beforeEach, I think it's better to call them before every tests.
=> Remove event listeners on unmount in useFlag and useVariant

src/useVariant.test.tsx, src/useVariant.ts
As described in #129, the react SDK didn't take into account if a variant's payload had changed when getting updates, resulting in potentially stale data. 
This PR addresses that by checking all parts of the variant before  determining whether it has changed.
Closes #129
=> fix(#129): detect variant payload change in useVariant hook

package.json, src/integration.test.tsx, src/useVariant.ts, yarn.lock
Fixes an issue where `useVariant` would not listen to changes in the `feature_enabled` property.
Should we bump the `unleash-proxy-client` peer dependency?
=> fix: react to feature_enabled changes

package.json
Bumps `unleash-proxy-client` peer dependency to `^3.2.0`.
=> chore: bump proxy-client peer dep

src/FlagProvider.tsx
Fallback when `startTransition` isn't supported, notably in React <18.
Closes #151
I did have to do something a little hacky to trip up webpack's export analysis. I originally tried the `.toString()` version that's suggested in the linked webpack issue but that made the typescript inference break.
I wasn't sure how to write tests but I did test this across 2 repos, one with React 16 and one with React 17 and it seems to work fine.
=> fix: fallback for startTransition for React <18

package.json, src/FlagProvider.tsx, yarn.lock
This PR fixes a bug where errors would not be cleared out and kept in state.
**How**
In the parent SDK we emit a 'recovered' event when the network call is successful following an errored HTTP call. In this SDK we listen to the recover event and set the error state to `null`.
=> fix: clear stale errors

src/useFlag.ts, src/useVariant.ts
Make it more intuitive what is an expected parameter for `useFlag` and `useVariant`.
=> docs: rename parameters related to feature name

README.md, src/FlagProvider.test.tsx, src/FlagProvider.tsx
This PR will allow the `startClient` option to be used even if you pass in a config. This change should be backwards compatible as the startClient option is defaulted to `true`. We consider it a bug that startClient does not work when you pass in the config option. 
Solves #161
=> fix: allow start client to be used for config

.github/workflows/build.yml, package.json, src/FlagContext.ts, src/FlagProvider.tsx, src/useFlagStatus.test.tsx, yarn.lock
There was a bug where the flagsReady status, returned from the useFlagsStatus hook, remains false even when an already started Unleash client is passed to the Unleash flag provider. This occurred despite the client being initialized and ready.
Closes #168
=> fix: provider initialization

src/FlagProvider.tsx
Unleash SDK uses startTransition under the hood. RN 0.75 and 0.76 (latest) break on startTransition (https://github.com/facebook/react-native/pull/44586). React itself removed internal _callbacks set on the transition (https://github.com/acdlite/react/commit/12a387d95e81a9507ade8fb796ded27615188c2f) while RN still has it.
This PR performs feature detection to find if the code is running in RN and skips startTransition in a similar way as we do for older React versions.
Ideally this PR should not be needed but until RN supports the new startTransition we may need to have this fallback.
=> fix: avoid startTransition in React Native

README.md
Document startTransition in ReactNative
Addresses: https://github.com/Unleash/proxy-client-react/pull/178#issuecomment-2504796411
=> docs: startTransition in React Native

.github/workflows/release.yml
Updates the release template to use the new npm release v2 action, which relies on the GitHub bot instead of a personal PAT.
=> Meta: update release template to use npm release v2

package.json, yarn.lock
Updates the dependency on the underlying Unleash client to 3.7.1. This
version of the client adds new `x-unleash` headers which lets Unleash
count unique connections and see SDK version information.
=> feat: add sdk uniqueness headers

package.json, yarn.lock
This update includes uuid generation that doesn't rely on the `crypto` module for connection id.
=> fix: update proxy client dep to 3.7.2

README.md
Just a trivial readme update;
"Listening to events" section of README.md imports `useUnleashContext` instead of `useUnleashClient`.
=> docs: fix wrong import in events section of README.md

README.md, src/useFlagContext.test.ts, src/useFlagContext.ts
Instead of throwing if the context is not provided, we'll console.error the message instead.
=> fix: console.error

README.md
Move note for 4.0.0 under the v4 migration path header.
=> docs: add note on v4 under the v4 migration header

src/FlagProvider.tsx
- #193 
Implemented useCallback to maintain stable function references across render cycles. This prevents performance issues caused when unmemoized functions create new instances on each render.
- `FlagProvider.tsx:109-150`
=> Fix context value reference changing across rendering

src/FlagProvider.tsx
Removing changes from #196
See conversation here: https://github.com/Unleash/proxy-client-react/issues/193#issuecomment-2792378632
In short, this was not the root cause of the issue. There are some additional re-renders when state or error is changing, but that will require more significant refactors.
=> revert context method changes

README.md, package.json
=> chore: change repo references
