README.md
Hello, I've just installed your product to a react native app. That was a bit difficult to understand how to configure it with React Native, so I propose you this modification to your readme file.
=> fix: readme add react-native procedure

src/index.ts, src/useUnleashClient.test.ts, src/useUnleashClient.ts
=> feat: add use unleash client hook

.vscode/settings.json, src/FlagContext.ts, src/FlagProvider.test.tsx, src/FlagProvider.tsx, src/useFlag.ts, src/useFlagsStatus.ts, src/useUnleashClient.ts, src/useVariant.ts
- Improve `FlagContext` type. so you can delete manual typing via `as`.
- **src/FlagContext.ts**: it contains `IFlagContextValue` interface. 
I'd like to do refactor `useVariant` typing, but I'd like to hear your opinions before that. how do you think If I refactor like this?:
```ts
type VariantPayload<TPayloadValue> =
| JsonVariantPayload<TPayloadValue>
| CsvVariantPayload
| StringVariantPayload;
type IUseVariantResult<TPayloadValue> = {
name: string;
enabled: boolean;
payload?: VariantPayload<TPayloadValue>;
};
const useVariant = <TPayloadValue extends {}>(
name: string
): IUseVariantResult<TPayloadValue> => {
// ...
}
```
[(TS Playground)](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgzgewHYDUCGAnAlmpwAKaIANgmgCYA8AKoSWeesQK4QB8UAvFAN4CwAKChRQkAFxQA5ACtESSQG5BwgG5oWECbSKkKTVkoEB …
=> refactor: improve context type

README.md
Fixes https://github.com/Unleash/proxy-client-react/issues/60.
=> docs: update examples to React 18

src/index.ts, src/useFlags.ts
=> issue#79 add useFlags hook

package.json, src/useFlags.test.ts, src/useFlags.ts, src/useUnleashContext.test.ts
Listen to `UPDATE` event in `useFlags`.
Closes #106
=> fix: update flags on context update

.gitignore, package.json
Update JS client version to support variant metrics. Bumping up minor version as our transitive dependency adds a new capability to the React client.
=> Metric variants support

package.json, yarn.lock
Sync unleash client dev dep with peer dep.
=> Update dev dep

README.md
https://unleash-community.slack.com/archives/C03GWTN7XMG/p1684439480055559
=> Add initial context to README

src/FlagProvider.tsx
Closes # No issue created
Flag error was never set because error was assigned to `flagsErrorRef.current` first and next condition -` flagsErrorRef.current === null` was never `true`
=> Fix FlagProvider error callback

src/FlagProvider.tsx
- Wrapping setState inside FlagProvider with startTransition to prevent hydration error
- See issue #124 for more information
Closes #124 
...
=> fix: hydration error from state update in FlagProvider (#124)

README.md, package.json
Adds a note for v4.0.0 in README
=> chore: add note for major release v4

package.json
=> fix: add types property to package.json

package.json, src/index.ts
Closes https://github.com/Unleash/proxy-client-react/issues/138
=> fix: storage provider type

package.json
Fix `exports` paths. Closes https://github.com/Unleash/proxy-client-react/issues/142
=> fix: package exports

package.json, src/integration.test.tsx, yarn.lock
Fixes a test assumption after https://github.com/Unleash/unleash-proxy-client-js/pull/180
=> test: fix variant result assumption

.github/workflows/build.yml, package.json, yarn.lock
- upgrade dependencies
- make sure `unleash-proxy-client` peer dependency is up to date
=> chore: update dependencies

package.json, yarn.lock
This version bump contain abort controller fix: https://github.com/Unleash/unleash-proxy-client-js/pull/207
=> chore: update js client version

package.json
=> chore: update peer dependency version

.github/workflows/build.yml
- Use enforce use of yarn.lock
- Test on current version of Node
This should fix build issues in other PRs
=> fix: update build pipeline
